### ISSUE TITLE
SocketTimeoutException when uploading big files to Google Drive

### ISSUE THREAD

**Issue by wonderfly** [google/google-api-java-client#853]
_From [ArmenPol...@gmail.com](https://code.google.com/u/101600603580442776101/) on January 15, 2014 02:43:07_

google-api-java-client 1.15.0-rc

Java environment:  Java 5

When I try upload file ~1.5Gb to Google Drive I've got java.net.SocketTimeoutException.
I use MediaHttpUploader in resumeable mode + configured IOExceptionHandler and UnsuccessfulResponseHandler with ExponentialBackOff:

``` java
HttpBackOffUnsuccessfulResponseHandler responseHandler = new HttpBackOffUnsuccessfulResponseHandler(new ExponentialBackOff());
request.setUnsuccessfulResponseHandler(responseHandler);
request.setIOExceptionHandler(new HttpBackOffIOExceptionHandler(new ExponentialBackOff()));
request.setConnectTimeout(40000);
request.setReadTimeout(100000);
```

So file started uploading by chunks and after some time GDrive could fire exception indicating that token expiration or any other exception could happen. So MediaUploader is trying to retry request. It sends it again (token refreshed successfully) but got timeout exception, then backoff is triggered and it request was sent again, bug got same result - socket timeout. It tries 10 times, overall several minutes - same effect. So upload is canceled and our application, after some time, tries to repeat file upload, but same issue rised again - in case any errors happened while file uploading, socket timeout exception thrown and no chance to resume uploading.
I've attached

**Attachment:** [socket_timeout.log](http://code.google.com/p/google-api-java-client/issues/detail?id=853)

_Original issue: http://code.google.com/p/google-api-java-client/issues/detail?id=853_

**Comment by derrenbrown** [comment]
I am having a similar issue.

Basically, my Google App Engine application uploads plain text files to Google Drive and has them converted to Doc format. The text files are only a few megabytes big tops. But I run into this error quite often (after 30 seconds):

```
Uncaught exception from servlet
java.net.SocketTimeoutException: Timeout while fetching URL: https://www.googleapis.com/upload/drive/v2/files?convert=true&uploadType=resumable&upload_id=AEnB2Ur9cMfwoGw6gQebEvEsjSfyQnfkFOwRMzLCgl7DKdKOlb1sCA1X-rkrijX6wbDSz1Sd2MT9V0Wu59fIWxn-NE-v1LULhw
	at com.google.appengine.api.urlfetch.URLFetchServiceImpl.convertApplicationException(URLFetchServiceImpl.java:145)
	at com.google.appengine.api.urlfetch.URLFetchServiceImpl.fetch(URLFetchServiceImpl.java:45)
	at com.google.apphosting.utils.security.urlfetch.URLFetchServiceStreamHandler$Connection.fetchResponse(URLFetchServiceStreamHandler.java:419)
	at com.google.apphosting.utils.security.urlfetch.URLFetchServiceStreamHandler$Connection.getInputStream(URLFetchServiceStreamHandler.java:298)
	at com.google.apphosting.utils.security.urlfetch.URLFetchServiceStreamHandler$Connection.getResponseCode(URLFetchServiceStreamHandler.java:151)
	at com.google.api.client.http.javanet.NetHttpResponse.<init>(NetHttpResponse.java:36)
	at com.google.api.client.http.javanet.NetHttpRequest.execute(NetHttpRequest.java:94)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:965)
	at com.google.api.client.googleapis.media.MediaHttpUploader.executeCurrentRequestWithoutGZip(MediaHttpUploader.java:545)
	at com.google.api.client.googleapis.media.MediaHttpUploader.resumableUpload(MediaHttpUploader.java:417)
	at com.google.api.client.googleapis.media.MediaHttpUploader.upload(MediaHttpUploader.java:336)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:418)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
```

My code looks something like this:
```
		Drive.Files.Insert insertRequest = driveService.files()
				.insert(fileMetadata, byteArrayContent).setConvert(true);
		File insertedFile = insertRequest.execute();
```

I hope this bug can be fixed asap. Thanks.

**Comment by rSuryaKantDhya** [comment]
hello. were you able to solve this issue. I got stuck on similar issue. I am trying to upload large PDF file to google drive . But it is either showing me socket time out exception or any other random exception

**Comment by ejona86** [comment]
You can try changing the read timeout with `HttpRequest.setReadTimeout()`. You can get access to the `HttpRequest` by implementing a `HttpRequestInitializer` and then calling `setHttpRequestInitializer()` on the client builder.

**Comment by IvanRF** [comment]
I'm also facing this issue. What @ejona86 mentions is explained here: [Timeouts and Errors](https://developers.google.com/api-client-library/java/google-api-java-client/errors).
However, there it also says:

> When an error status code is detected in an HTTP response to a Google API that uses the JSON format, the generated libraries throw a GoogleJsonResponseException.

and this is not happening. Instead of a `GoogleJsonResponseException` we are getting a `SocketTimeoutException`.
