### ISSUE TITLE
UnsupportedOperationException when using HttpClient 4.3.x

### ISSUE THREAD

**Issue by i386** [google/google-api-java-client#928]
HttpClient.getParams() was deprecated in HttpClient 4.3 which causes an incompatibility with the Google Java Client when using the `HttpClientBuilder` with the `ApacheHttpTransport`.

For example `new ApacheHttpTransport(HttpClientBuilder.create().build());` will throw `java.lang.UnsupportedOperationException`

```
    at org.apache.http.impl.client.InternalHttpClient.getParams(InternalHttpClient.java:206)
    at com.google.api.client.http.apache.ApacheHttpTransport.<init>(ApacheHttpTransport.java:129)
    at com.xxxx.google.GoogleService.<init>(GoogleService.java:135)
```

**Comment by joeyvmason** [comment]
+1

**Comment by jmif** [comment]
+1

**Comment by giltroymeren** [comment]
+1

**Comment by mattwhisenhunt** [comment]
Now tracking at https://github.com/google/google-http-java-client/issues/250
