### ISSUE TITLE
setForMine(true) causes invalidSearchFilter error

### ISSUE THREAD

**Issue by rgal75** [google/google-api-java-client#935]
If I call
```
YouTube.Search.List.setForMine(true);
```
then I get the following error even though `YouTube.Search.List.setType("video")` is also called as required by the use of `YouTube.Search.List.setForMine(true)`:
```
There was a service error: 400 : Invalid combination of search filters and/or restrictions.
hu.pocketguide.kmlvideo.youtube.exception.YouTubeException: Service error.
	at com.google.api.services.samples.youtube.cmdline.data.PgFindByKmlId.findVideosByKmlId(PgFindByKmlId.java:107)
	at com.google.api.services.samples.youtube.cmdline.data.PgFindByKmlId.main(PgFindByKmlId.java:62)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.codehaus.mojo.exec.ExecJavaMojo$1.run(ExecJavaMojo.java:293)
	at java.lang.Thread.run(Thread.java:745)
Caused by: com.google.api.client.googleapis.json.GoogleJsonResponseException: 400 Bad Request
{
  "code" : 400,
  "errors" : [ {
    "domain" : "youtube.search",
    "location" : "",
    "locationType" : "parameter",
    "message" : "Invalid combination of search filters and/or restrictions.",
    "reason" : "invalidSearchFilter"
  } ],
  "message" : "Invalid combination of search filters and/or restrictions."
}
	at com.google.api.client.googleapis.json.GoogleJsonResponseException.from(GoogleJsonResponseException.java:145)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:113)
	at com.google.api.client.googleapis.services.json.AbstractGoogleJsonClientRequest.newExceptionOnError(AbstractGoogleJsonClientRequest.java:40)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest$1.interceptResponse(AbstractGoogleClientRequest.java:312)
	at com.google.api.client.http.HttpRequest.execute(HttpRequest.java:1049)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:410)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.executeUnparsed(AbstractGoogleClientRequest.java:343)
	at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
	at com.google.api.services.samples.youtube.cmdline.data.PgFindByKmlId.findVideosByKmlId(PgFindByKmlId.java:100)
	... 7 more
```
The same query in the Try it! section of https://developers.google.com/youtube/v3/docs/search/list works.

**Comment by rgal75** [comment]
I've found the problem. I failed to pass an appropriate Credential object to ```new YouTube.Builder(...)```. With the following initialization it works:
```
List<String> scopes = Lists.newArrayList("https://www.googleapis.com/auth/youtube.readonly");
Credential credential = Auth.authorize(scopes, "mycredentialdatastore");
            youtube = new YouTube.Builder(
                    Auth.HTTP_TRANSPORT,
                    Auth.JSON_FACTORY,
                    credential).setApplicationName("mysample").build();
```
Still, I find the error message ("Invalid combination of search filters and/or restrictions.") misleading.
