### ISSUE TITLE
Failures with signatures?

### ISSUE THREAD

**Issue by mikebell90** [google/google-api-java-client#947]
Just started today:

```
java.security.SignatureException: Signature length not correct: got 256 but was expecting 128
	at sun.security.rsa.RSASignature.engineVerify(RSASignature.java:190)
	at java.security.Signature$Delegate.engineVerify(Signature.java:1194)
	at java.security.Signature.verify(Signature.java:627)
	at com.google.api.client.util.SecurityUtils.verify(SecurityUtils.java:159)
	at com.google.api.client.json.webtoken.JsonWebSignature.verifySignature(JsonWebSignature.java:377)
	at com.google.api.client.googleapis.auth.oauth2.GoogleIdTokenVerifier.verify(GoogleIdTokenVerifier.java:174)
	at com.google.api.client.googleapis.auth.oauth2.GoogleIdToken.verify(GoogleIdToken.java:79)
	at com.speakeasy.server.google.GoogleOAuthClient.exchangeAuthCodeForTokens(GoogleOAuthClient.java:264)
```

similar report other people being affected:

http://stackoverflow.com/questions/30780407/google-oauth2-jwt-token-verification-exception

**Comment by bes** [comment]
I got this too, along with a lot of other people. This has to hurt a lot if you are using API endpoints.

**Comment by Simtay** [comment]
Same problem here using 1.18.rc

**Comment by ejona86** [comment]
You should no longer be getting this error.

**Comment by Simtay** [comment]
The problem persists.

**Comment by ejona86** [comment]
@Simtay, make sure to clear any auth cache you may have. Others on StackOverflow are reporting the problem was resolved.

**Comment by aaronharnly** [comment]
Google servers are now returning certificates of the same length, but the bug in the library (not handling the exception raised when a signature is not the expected length) persists.

**Comment by mikebell90** [comment]
@JustinBeckwith not sure why you are assigning me a long closed ticket, even though I did open it ;l)
