### ISSUE TITLE
IllegalArgumentException while parsing Google Webmasters api response

### ISSUE THREAD

**Issue by darshanmehta10** [google/google-api-java-client#959]
_From @darshanmehta10 on August 17, 2015 21:40_

I am using google java client to get feed from webmasters using below code:

```
public void testWebmasters(String token){
    try{
        Credential credential = getCredential(token);
        Webmasters service = new Webmasters.Builder(HTTP_TRANSPORT, JSON_FACTORY, credential)
        .setApplicationName("WebmastersCommandLine")
        .build();
        com.google.api.services.webmasters.Webmasters.Sites.List list = service.sites().list();
        SitesListResponse execute = list.execute();
        List<WmxSite> siteEntry = execute.getSiteEntry();
        System.out.println(service.getObjectParser().getClass());
        for(WmxSite site : siteEntry){
            System.out.println(site.getSiteUrl());
            System.out.println(site.getPermissionLevel());
            SearchAnalyticsQueryRequest request = new SearchAnalyticsQueryRequest();
            request.setStartDate("2015-08-01");
            request.setEndDate("2015-08-05");
            request.setDimensions(new ArrayList<String>(){{add("date");}});
            SearchAnalyticsQueryResponse response = service.searchanalytics().query(site.getSiteUrl(), request).execute();
            for(ApiDataRow row : response.getRows()){
                System.out.println(row.getClicks());
                System.out.println(row.getImpressions());
                System.out.println(row.getCtr());
                row.getPosition();
            }
        }
    }catch(Exception e){
        e.printStackTrace();
    }
}
```

On line (`SearchAnalyticsQueryResponse response = service.searchanalytics().query(site.getSiteUrl(), request).execute();`)  am getting below exception:

```
java.lang.IllegalArgumentException: key ctr
at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:871)
at com.google.api.client.json.JsonParser.parse(JsonParser.java:374)
at com.google.api.client.json.JsonParser.parse(JsonParser.java:347)
at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:87)
at com.google.api.client.json.JsonObjectParser.parseAndClose(JsonObjectParser.java:81)
at com.google.api.client.http.HttpResponse.parseAs(HttpResponse.java:459)
at com.google.api.client.googleapis.services.AbstractGoogleClientRequest.execute(AbstractGoogleClientRequest.java:460)
at ...
Caused by: java.lang.IllegalArgumentException: key ctr, field private java.util.List com.google.api.services.webmasters.model.SearchAnalyticsQueryResponse.rows
at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:871)
at com.google.api.client.json.JsonParser.parse(JsonParser.java:462)
at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:771)
... 8 more
Caused by: java.lang.IllegalArgumentException: key ctr, field private java.util.List com.google.api.services.webmasters.model.SearchAnalyticsQueryResponse.rows
at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:871)
at com.google.api.client.json.JsonParser.parseArray(JsonParser.java:638)
at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:730)
... 10 more
Caused by: java.lang.IllegalArgumentException: key ctr, field private java.lang.Double com.google.api.services.webmasters.model.ApiDataRow.ctr
at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:871)
at com.google.api.client.json.JsonParser.parse(JsonParser.java:462)
at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:771)
... 12 more
Caused by: java.lang.IllegalArgumentException: number field formatted as a JSON string must use the @JsonString annotation
at com.google.api.client.repackaged.com.google.common.base.Preconditions.checkArgument(Preconditions.java:92)
at com.google.api.client.util.Preconditions.checkArgument(Preconditions.java:49)
at com.google.api.client.json.JsonParser.parseValue(JsonParser.java:836)
... 14 more
```

On investigating further, I found that api response contains (`"ctr": "NaN"`) as one of the key-value pairs and as `ctr` property of `ApiDataRow` class doesn't have `@JsonString` annotation, it is throwing this error.

Below is the sample response which causes the api to fail:

```
{
 "rows": [
  {
   "keys": [
    "2015-08-01"
   ],
   "clicks": 0,
   "impressions": 0,
   "ctr": "NaN",
   "position": "NaN"
  }
 ]
}
```

This is the code to reproduce the exception without calling google api:

```
JacksonFactory factory = new JacksonFactory();
SearchAnalyticsQueryResponse response = factory.fromReader(new FileReader("G:\\response.txt"), SearchAnalyticsQueryResponse.class);
```

Is there any way to resolve this without changing model class? I am already using latest version of google-api-services-webmasters dependency.

Thanks in advance.

_Copied from original issue: google/gdata-java-client#458_

**Comment by daannijkamp** [comment]
@darshanmehta10 I have the same problem. Have you found a way to solve this?

**Comment by cburns93** [comment]
Was this ever resolved?

**Comment by mattwhisenhunt** [comment]
Thank you for your bug report. This client library is currently in maintenance mode. We are fixing necessary bugs and adding essential features to ensure this library continues to meet your needs for accessing Google APIs.
It looks like this is a problem in the autogenerated google-api-services-webmasters. 
After careful consideration, we have decided not to fix this bug since there is an acceptable work-around. If you disagree, please feel free to explain why you believe fixing it is essential for users of this client library.

**Comment by daannijkamp** [comment]
@mattwhisenhunt what is the "acceptable work-around" ? Don't use statically typed programming language?

**Comment by mattwhisenhunt** [comment]
You should be able to either test for ctr in a caught IllegalArgumentException or extend SearchAnalyticsQueryResponse with a annotated ctr member.
